development:
  adapter: postgresql
  encoding: unicode
  database: aliens-development

test:
  adapter: postgresql
  encoding: unicode
  database: aliens-test

production:
  adapter: postgresql
  encoding: unicode
  database: aliens-prod
